### PR TITLE
Clarify the maximum number of roots sentence.

### PR DESCRIPTION
**Pull request by bcomnes**
This sentence is slightly unclear, and slightly contradictory to the statement preceding it.  Adding a few extra words of clarification improves its intention.

### CODE REVIEW

**Comment by pfrazee** [comment]
@bnewbold yeah I think that's a good improvement

**Comment by bcomnes** [comment]
Agreed, justifying why we want a single fixed size hash is +1.

"To encode in the Hypercore feed" Is ambiguous.  Encoded in the merkle tree forever? Encoded by convention until there are a different set of roots?

**Comment by bcomnes** [comment]
"We always want a way to refer to a single fixed-size hash of the hypercore feed.  Therefore, when there are multiple roots, we re-hash all the individual root hashes together into a single hash value. At most there will be log2(number of data blocks) such individual root hashes to re-hash."

Something like that, plus clarification on where that fixed size hash is stored / encoded?  Is my understanding correct in that this hash doesn't ever end up in the feed?

**Comment by bnewbold** [comment]
Merged PR #29, which was a variant on this.

**Comment by bnewbold** [comment]
Thank you @bcomnes!

**Pull request closed without merging**
